"""remove_confidence_field

Revision ID: a2fecd9184ac
Revises: 5cd943e27d08
Create Date: 2025-07-20 15:48:41.905864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fecd9184ac'
down_revision: Union[str, Sequence[str], None] = '5cd943e27d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
